### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by f3r10** [bitcoindevkit/bdk-sqlx#5]
- replicate every test that rusqlite has in the bdk repo
- test that creates two wallets and loads them
- test that syncs with electrum and persists the blockchain data

**Comment by matthiasdebernardini** [comment]
I'll be adding a test that lists transactions and makes sure that the no persist wallet and the persist wallet have the same list. I'm running into an issue where this isn't the case.

I think adding a similar test for utxos would also be valuable.

@ValuedMammal how do the different blockchain sources impact the tx graph? Can we assume that they all work the same? Otherwise, should we test with esplora as well?

**Comment by ValuedMammal** [comment]
Data that makes its way into the tx-graph will look the same, but I'm not sure we can assume that different blockchain sources will update the graph with the same data. (specifically I'm thinking about anchors, previous txouts, etc). Ideally it would be the same, but that's my hunch based on the fact that `bdk_electrum` and `bdk_esplora` are different implementations.
